<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2016/12/11
 * Time: 14:37
 */
namespace admin\models;

use yii\base\Model;

class System extends Model
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }
}