<?php
/**
 * Created by PhpStorm.
 * User: layery
 * Date: 17-2-23
 * Time: 下午8:51
 */
namespace frontend\controllers;

use yii;
use common\models\Redis;
use yii\web\controller;
class TestController extends Controller {
    public $str;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $str = 'filename.jpg.png';
        $this->str = $str;
    }

    public function actionStrpos()
    {
        $mystring = 'sssabc';
        $findme   = 'sss';
        $pos = strpos($mystring, $findme);
        // 注意这里使用的是 ===。简单的 == 不能像我们期待的那样工作，
        // 因为 'a' 是第 0 位置上的（第一个）字符。
        if ($pos === false) {   // 如果被查找字符串再待查找字符串中未发现
            echo '在'. $mystring . '不中存在' . $findme;
        } else {
            echo '在'. $mystring . ' 中存在' . $findme;
        }


    }
    
	public function actionIndex()
	{
        return $this->render('index');
    }
    
    public function actionCurl()
    {
       $url = 'http://apis.haoservice.com/weather';
       $curl = curl_init();
       $curl = yii::$app->curl;
       $curl->setOption('cityname', '北京');
       $curl->setOption('dtype', 'json');
       $curl->setOption('key', 'f2fbad4fc2abe247368fe18ba836a75b');
       $rs = $curl->get($url);
       p($rs);
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}
