<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2016/12/12
 * Time: 23:49
 */

namespace admin\controllers;
use admin\models\Article;
use yii;

class ArticleController extends BaseController
{
    public $js = [];
    public function init()
    {
        parent::init();
    }

    public function beforeAction($action)
    {
        if (Yii::$app->controller->action->id == 'create') {
            $this->js = [
                JS_URL . "/uedit/ueditor.all.min.js",
                JS_URL . "/uedit/ueditor.config.js"
            ];
        }
        if (!empty($this->js)) {
            foreach ($this->js as $v ) {
                $this->view->registerJs($v[0]);
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function beforeRender()
    {

    }
    public function actionList()
    {
        $data = (new Article())->getList();
        return $this->render('list', ['data' => $data]);
    }

    public function actionCreate()
    {
        if (IS_POST) {

        }
        return $this->render('_add');
    }
}