<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2017/3/26
 * Time: 16:53
 */
namespace admin\controllers;

use common\models\Cate;
use common\query\AuthQuery;
use yii;
use common\models\Auth;
use common\util\CommonUtil;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use \ReflectionClass;

class AuthController extends BaseController
{

    private $model;
    public $enableCsrfValidation = true;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new Auth();
    }

    /**
     * 权限列表
     *
     * @return string
     */
    public function actionList()
    {
        $dataProvider = [];
        $post = yii::$app->request->post();
        $post['name'] = 'llf';
        if (!empty($post)) {
            $dataProvider = $this->model->dataList();
        }
        return $this->render('list', ['dataProvider' => $dataProvider]);
    }

    /**
     * 创建权限
     *
     * @return string
     */
    public function actionCreate()
    {
        if (!empty(yii::$app->request->post())) {
            $params = [
                'name' => CommonUtil::post('name'),
                'status' => CommonUtil::post('status'),
                'actions' => json_encode(CommonUtil::post('actions')),
                'uid' => 1,
                'created_at' => time(),
                'updated_at' => time()
            ];
            $rs = (new Auth())->AuthCreate($params);
        }
        return $this->render('permission_create');
    }

    /**
     * Rbac创建权限
     *
     */
    public function actionPermissionCreate()
    {
        p('asdfasdf');
//        $name = CommonUtil::post('permissionName');
//        $auth = Yii::$app->authManager;
//        $createPost = $auth->createPermission($name);
//        $createPost->description = '创建了 ' . $name. ' 权限';
//        $auth->add($createPost);
        return $this->render('PermissionCreate');
    }

    public function actionAjaxChangeStatus()
    {
        p('asdfasdf');
        $id = CommonUtil::post('id', 'int');
        p($id);
    }

    public function actionTest()
    {
        $reflectionObject = new ReflectionClass($this);
        $controllerId = yii::$app->controller->id;
        $methodList = $reflectionObject->getMethods(\ReflectionMethod::IS_PUBLIC);
        $methodArray = [];
        foreach ($methodList as $v) {
            if ($v->class == $reflectionObject->name) {
                $methodArray[] = $controllerId. '/'. str_replace('action', '', $v->name);
            }
        }
        return $this->renderContent('rbactest');
    }
}