<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2017/3/26
 * Time: 16:53
 */
namespace admin\controllers;

use common\models\Cate;
use common\query\AuthQuery;
use yii;
use common\models\Auth;
use common\util\CommonUtil;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use \ReflectionClass;

class AuthController extends BaseController
{

    private $model;
    public $enableCsrfValidation = false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new Auth();
    }

    /**
     * 角色列表
     *
     * @return string
     */
    public function actionList()
    {
        $post = ['llf'];
        if (!empty($post)) {
            $dataProvider = $this->model->getRoleList();
        }
        return $this->render('list', ['dataProvider' => $dataProvider]);
    }

    /**
     * 创建权限节点
     *
     * @return string
     */
    public function actionCreate()
    {
        $msg = '';
        if (!empty(yii::$app->request->post())) {
            $params = [
                'controllerId' => CommonUtil::post('controllerId', 'string'),
                'actionId' => CommonUtil::post('actionId', 'string')
            ];
            $result = $this->model->createPermissions($params);
            if (is_array($result)) {
                $msg = $result[0];
            }
        }
        $permissionList = $this->model->getPermissions();
        $model = ['permission' => $permissionList, 'error' => $msg];
        return $this->render('permission_create', ['model' => $model]);
    }

    //
    public function actionRoleCreate()
    {
        exit('asdfasf');
//        $permissList = $this->model->getPermissions();
    }

}