<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2016/12/11
 * Time: 14:51
 */

namespace admin\controllers;
use yii;
use yii\web\Controller;

class BaseController extends Controller
{
    public $js = [];
    public $css = [];

    // 初始化引入所有的js , css文件
    public function init()
    {
        $this->layout = 'admin';
        $this->js = [
            [JS_URL . 'jquery-ui-1.10.3.custom.min.js'],
            [JS_URL . 'jquery.ui.touch-punch.min.js'],
            [JS_URL . 'jquery.slimscroll.min.js'],
            [JS_URL . 'jquery.easy-pie-chart.min.js'],
            [JS_URL . 'jquery.sparkline.min.js'],
            [JS_URL . 'flot/jquery.flot.min.js'],
            [JS_URL . 'flot/jquery.flot.pie.min.js'],
            [JS_URL . 'flot/jquery.flot.resize.min.js']
        ];
    }

   public function beforeAction($action)
   {
       return parent::beforeAction($action); // TODO: Change the autogenerated stub
   }
}