<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2016/12/12
 * Time: 23:49
 */

namespace admin\controllers;

use common\util\CommonUtil;
use yii;
use yii\db\Query;
use yii\data\ArrayDataProvider;
use common\models\Cate;

class CateController extends BaseController
{
    // 配置关闭csrf验证
    //public $enableCsrfValidation = false;

    private $model;

    public function init()
    {
        $this->model = new Cate();
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actionList()
    {
        $user = yii::$app->user->isGuest;
        if (IS_AJAX) {
            $params = !empty($_POST) ? $_POST : [];
            $result = $this->model->dataList($params);
            return $this->autoReturn($result, false);
        }
        $data = new ArrayDataProvider([
            'allModels' => Cate::find()->all()
        ]);
        return $this->render('list', ['data' => $data]);
    }

    public function actionCreate() {
        if (IS_POST) {
            $data = [
                'name' => yii::$app->request->post('name'),
                'introduce' => yii::$app->request->post('introduce'),
                'parent_id' => yii::$app->request->post('parent_id'),
                'dateline' => intval(time())
            ];
            $cate = new PCate();
            $result = $cate->create($data);
            return $result;
        }

        return $this->render('_add');
    }

    public function actionDelete()
    {
       if (IS_AJAX) {
           $id = CommonUtil::post('id', 'int');
           return $this->model->cateDelete($id);
       }
    }
}