<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2017/3/25
 * Time: 14:03
 */
namespace admin\controllers;

use admin\assets\AppAsset;
use common\models\User;
use yii\data\ArrayDataProvider;
use yii\db\Query;

class UserController extends BaseController
{
    private $model;

    public function init()
    {
        $this->model = new User();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        $query = new Query();
        $data = new ArrayDataProvider([
            'allModels' => $query->from(User::tableName())->all(),
        ]);
        return $this->render('list', ['data' => $data]);
    }
}