<?php
/**
 * Created by PhpStorm.
 * User: 未定义
 * Date: 2017/3/25
 * Time: 14:03
 */
namespace admin\controllers;

use admin\assets\AppAsset;
use yii;
use common\models\User;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\Query;

class UserController extends BaseController
{
    private $model;

    public function init()
    {
        $this->model = new User();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
            'pagination' => [
                'pageSize' => '10'
            ]
        ]);
        return $this->render('list', ['dataProvider' => $dataProvider]);
    }

    /**
     * @return string
     */
    public function actionDetail()
    {
        return $this->renderContent('用户详情');

    }
}